### ISSUE TITLE
Unimplemented functions

### ISSUE THREAD

**Issue by latot** [DHrpcs3/rpcs3#1000]
Hi again, i got this messages when i try to load the game Dengeki Bunko Fighting Climax, well here is the log:

https://gist.github.com/latot/f1b77b73544ee38b65ba

Cya.

**Comment by Syphurith** [comment]
@latot As you see there are quite many functions not implemented yet, as rpcs3 is in WIP state now. You can try to implement those with some documents about PS3's API (if so go to the irc and ask for its name), or just wait for them be done by others. And also the list may be only part of those.

**sceNp is not a part of the core functions of PS3 iirc.** (It should be related to PS Online features.) So you could just try to run it to see how far you could achieve in the gameplay now.

And for those function with only a function id, its module is not done, or its API (only in higher FW than 3.55, or what listed in PS3Devwiki) is not found. Currently i can only suggust you continue to run it, or have a look at doc and try complete the function.

**Comment by latot** [comment]
Oks, thx, unfortunately I have not sufficient knowledge to help with functions, and about the game this still does not run, i think i'll make a new issue with that, and i'll close this.

Thx
