### ISSUE TITLE
Erreur to lunch the rpcs3-x64.exe - MSVCP110.dll missing

### ISSUE THREAD

**Issue by ychoucha** [DHrpcs3/rpcs3#1042]
Hello i have this erreur :100: 
![issues dhrpcs3rpcs3 - mozilla firefox](https://cloud.githubusercontent.com/assets/301074/6770556/9be9cbb6-d0c3-11e4-919c-d3d83dda3473.jpg)
hwo fixit please ?

**Comment by O1L** [comment]
http://www.microsoft.com/en-us/download/details.aspx?id=40784

**Comment by tambry** [comment]
Not a real issue. Though I think we have another "sakura leite costa", but this time a little better than him.

**Comment by ychoucha** [comment]
not working

i have installed it, and not working

**Comment by tambry** [comment]
@ychoucha What operating system do you use?

**Comment by Syphurith** [comment]
@ychoucha Please take a look:
* MSVCP110.DLL is in MSVC2012. You would need to install [This](http://www.microsoft.com/en-us/download/details.aspx?id=30679)
* Rpcs3 should be built with MSVC2013. So i doubt why you would need 2012 redist.
* There is no X86 support, you would have to get a 64-bit system.

**Comment by ychoucha** [comment]
Hello,

so first i have windows 7 64x
i have installed the c++ 2013 : 
![visualc 2013](https://cloud.githubusercontent.com/assets/301074/6785602/e1dc1570-d186-11e4-93b2-2331bbbbdba1.jpg)


and i sill have the problem when i lunch the programm : 

![rpcs3-x64 exe - erreur systeme](https://cloud.githubusercontent.com/assets/301074/6785619/fac0589e-d186-11e4-9747-5298383c2da7.jpg)

so what is wrong ?

**Comment by Zangetsu38** [comment]
Pourquoi il te demande le MSVCP110, ce fichier n'a rien a voir avec visual studio 2013, ya une erreur quelque part, compile le avec visual studio 2013

**Comment by ychoucha** [comment]
c'est qu'elle visual studio qu'il faut utiliser : 

http://www.microsoft.com/france/visual-studio/essayez/download.aspx ?

**Comment by Zangetsu38** [comment]
le 2013 j'ai dis, prend le 2013 ultimate avec le SP4 inclut ici https://formulaires.microsoft.fr/page/BHDSID-Telecharger-VisualSudio/?SOURCE=EVALUATION&FU=ULT

**Comment by paulsapps** [comment]
Run depends.exe on each DLL it is using, this will show which one is to blame
