### ISSUE TITLE
cellMS functions

### ISSUE THREAD

**Issue by Ru4slan** [DHrpcs3/rpcs3#948]
I find many this functions in three games:
Wanted Corp [BLES-01416],Wakeboarding HD [NPUB-30098] and SEGA MEGA DRIVE Ultimate Collection [BLES-00475]
This three games show access violation.Maybe, cellMS function not released?Functions:
cellMSSystemGetNeededMemorySize
__cellMSSystemInitBasic
cellMSSystemClose
cellMSSystemSignalSPU
cellMSCoreGetRouting8
cellMSCoreGetRouting
cellMSCoreGetDSPParamAddr
cellMSCoreGetDSPHandle
cellMSCoreGetPause
cellMSCoreGetBypass
cellMSCoreGetEQEnable
cellMSCoreGetEQ
cellMSCoreGetVolume64
cellMSCoreGetVolume8
cellMSCoreGetVolume1
cellMSCoreGetWetInGain
cellMSCoreGetMasks
cellMSCoreGetMask

cellMSCoreSetMasks
cellMSCoreSetMask
cellMSCoreBypassDSP
cellMSCoreSetDSP
cellMSCoreSetBypass
cellMSCoreSetEQEnable
cellMSCoreSetEQ
cellMSCoreSetVolume8
cellMSCoreSetVolume64
cellMSCoreSetVolume1
cellMSCoreSetWetInGain
cellMSCoreSetRouting8
cellMSCoreSetRouting
cellMSCoreRoutingInit
cellMSCoreSetPause
__cellMSBusInit
cellMSCoreStop
cellMSCoreInit
cellMSStreamGetPriorityBank
cellMSStreamGetPriorityLevel
cellMSStreamGetCurrentEnv
cellMSStreamGetMP3FramePos
cellMSStreamGetMP3FrameInfo
cellMSStreamGetCurrentPlayPos
cellMSStreamGetEnvBypass
cellMSStreamGetCallbackFunc
cellMSStreamGetCallbackData
cellMSStreamGetRoutingMask
cellMSStreamSetWetInGains
cellMSStreamSetPriorityBankMaxLimit
cellMSStreamSetPriorityBankThreshold
cellMSStreamSetPriorityBank
cellMSStreamSetPriorityLevel
cellMSStreamSetSecondReadSkip
cellMSStreamSetFirstReadSkip
cellMSStreamGetInfo
cellMSStreamGetStatus
cellMSStreamGetRouting
cellMSStreamGetRoutingWetDry
cellMSStreamSetEnvBypass
cellMSStreamSetSub
cellMSStreamSetSecondRead
cellMSStreamSetFirstRead
cellMSStreamSetRouting8 
cellMSStreamSetRoutingWet8
cellMSStreamSetRoutingDry8
cellMSStreamSetRouting
cellMSStreamSetRoutingWet
cellMSStreamSetRoutingDry
cellMSStreamClearRouting
__cellMSStreamInit
cellMSStreamOpen
cellMSStreamPlay
__cellMSStreamSetPitch
cellMSStreamSetInfo
cellMSStreamClose
cellMSStreamSetCallbackFunc
cellMSStreamSetCallbackData
cellMSDSPReset
cellMSDSPResetPage
cellMSDSPLoadDSPFromMemory
cellMSDSPLoadDSPFromFile
cellMSSurroundApplyToStreams
cellMSStreamSetSurroundInfo
cellMSStreamGetSurroundInfo
__getSourceAddr cellMSSurroundSetListener
cellMSSurroundGetInfoSize
cellMSSurroundActive
cellMSSurroundInitSource

**Comment by tambry** [comment]
That is the PS3's MultiStream library.

**Comment by Ru4slan** [comment]
These functions are implemented at the moment?

**Comment by tambry** [comment]
@Ru4slan No, they are used for sound as far as I know.

**Comment by Ru4slan** [comment]
tambry, I understood
