### ISSUE TITLE
OS X Build error: "Unsupported fmt::format argument"

### ISSUE THREAD

**Issue by devilmac** [DHrpcs3/rpcs3#982]
Hi all,

I just made a build of the RPCS3 but I have the error below. Can someone help me?

make
[ 10%] Built target asmjit
[ 10%] Generating something_that_never_exists
-- Found Git: /opt/local/bin/git (found version "2.2.2")
[ 10%] Built target GitVersion
[ 11%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/Emu/ARMv7/ARMv7Decoder.cpp.o
/Users/federico/Downloads/rpcs3/rpcs3/Emu/ARMv7/ARMv7Decoder.cpp:1218:4: warning: add explicit braces to avoid dangling else [-Wdangling-else]
                        else
                        ^
In file included from /Users/federico/Downloads/rpcs3/rpcs3/Emu/ARMv7/ARMv7Decoder.cpp:1:
In file included from /Users/federico/Downloads/rpcs3/rpcs3/cotire/rpcs3_CXX_prefix.hxx:4:
In file included from /Users/federico/Downloads/rpcs3/rpcs3/stdafx.h:61:
/Users/federico/Downloads/rpcs3/rpcs3/../Utilities/StrFmt.h:189:4: error: static_assert failed "Unsupported fmt::format argument"
                        static_assert(!sizeof(T), "Unsupported fmt::format argument");
                        ^             ~~~~~~~~~~
/Users/federico/Downloads/rpcs3/rpcs3/../Utilities/StrFmt.h:441:41: note: in instantiation of template class 'fmt::detail::get_fmt<unsigned long>'
      requested here
                        return std::string(fmt, fmt_start) + get_fmt<T>::text(fmt + fmt_start, fmt_len, arg) + format(fmt + fmt_end, len - fmt...
                                                             ^
/Users/federico/Downloads/rpcs3/rpcs3/../Utilities/Log.h:135:38: note: in instantiation of function template specialization
      'fmt::detail::format<unsigned long>' requested here
        log_message(type, sev, fmt::detail::format(fmt, strlen(fmt), fmt::do_unveil(args)...));
                                            ^
/Users/federico/Downloads/rpcs3/rpcs3/Emu/ARMv7/ARMv7Decoder.cpp:1258:2: note: in instantiation of function template specialization
      'log_message<unsigned long>' requested here
        LOG_NOTICE(ARMv7, "armv7_decoder_initialize() finished, g_opct.size() = %lld", g_opct.size());
        ^
/Users/federico/Downloads/rpcs3/rpcs3/../Utilities/Log.h:9:51: note: expanded from macro 'LOG_NOTICE'
#define LOG_NOTICE(logType, text, ...)            log_message(logType, Log::Notice,  text, ##__VA_ARGS__)
                                                  ^
1 warning and 1 error generated.
make[2]: *** [rpcs3/CMakeFiles/rpcs3.dir/Emu/ARMv7/ARMv7Decoder.cpp.o] Error 1
make[1]: *** [rpcs3/CMakeFiles/rpcs3.dir/all] Error 2
make: *** [all] Error 2

**Comment by paulsapps** [comment]
Should probably enable OSX on Travis-CI

**Comment by devilmac** [comment]
What do you mean? I don't know if what you said is right since I tried to build RPCS3 on my Mac.
Why I have to enable OS X on Travis-CI?

**Comment by Nekotekina** [comment]
He didn't mean you to enable, I think...
About the error: what compiler is used? I wonder why it doesn't show actual types of template specializations.

Try to cast g_opct.size() to (u64), maybe this error will get fixed (but another ones may appear).

**Comment by paulsapps** [comment]
Yeah sorry, I mean rpcs3 team enable building on OSX via Travis-CI, that way it should keep building OK

**Comment by devilmac** [comment]
Hi Nekotekina,

I don't know which compiler is used, but applied your suggestion it seems that building is going on.
Thanks :)

@paulsapps don't worry :)

**Comment by danilaml** [comment]
@Nekotekina isn't there a way to disable vita code from building as it is not needed (or is it) by rpcs3?
Errors in ARMv7 anyway.

**Comment by Nekotekina** [comment]
Hmm, there should be u32 instead of time_t.
Of course, you can disable any code that fails, but better to report it, I'll fix it later anyway, and I don't think that there are so much errors.

**Comment by tambry** [comment]
@devilmac Does this problem still persist?

**Comment by devilmac** [comment]
Hi @tambry 
I think this problem is resolved.

Sorry for the delay on this answer.
