### ISSUE TITLE
Error Linking rpcs3

### ISSUE THREAD

**Issue by latot** [DHrpcs3/rpcs3#997]
Hi, log of error of the compilation:

[ 97%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/__/Utilities/rFile.cpp.o
[ 98%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/__/Utilities/SSemaphore.cpp.o
[ 98%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/__/Utilities/Log.cpp.o
[ 98%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/__/Utilities/rPlatform.cpp.o
[100%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/__/Utilities/AutoPause.cpp.o
[100%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/__/Utilities/rMsgBox.cpp.o
Linking CXX executable ../bin/rpcs3
/usr/lib/gcc/x86_64-pc-linux-gnu/4.8.3/../../../../x86_64-pc-linux-gnu/bin/ld: CMakeFiles/rpcs3.dir/Emu/Memory/vm.cpp.o: referencia sin definir al símbolo 'shm_unlink@@GLIBC_2.2.5'
/lib64/librt.so.1: error adding symbols: DSO missing from command line
collect2: error: ld devolvió el estado de salida 1
rpcs3/CMakeFiles/rpcs3.dir/build.make:7360: recipe for target 'bin/rpcs3' failed
make[2]: *** [bin/rpcs3] Error 1
CMakeFiles/Makefile2:263: recipe for target 'rpcs3/CMakeFiles/rpcs3.dir/all' failed
make[1]: *** [rpcs3/CMakeFiles/rpcs3.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Bigpet** [comment]
does adding `rt` to `target_link_libraries` here https://github.com/DHrpcs3/rpcs3/blob/e61849c3c415c66ca564f018f79b44f212093425/rpcs3/CMakeLists.txt#L123 help ?

**Comment by Syphurith** [comment]
While linking the executable, `ld` didn't find the symbol shm_unlink, which should be on Glibc(ver 2.2.5). 
The function this symbol represents, "remove a shared memory object".
@Bigpet you are correct, this function comes from `POSIX Real-time Library (librt, -lrt)` (Searched the man-page for that function). This should help.

**Comment by latot** [comment]
Yay, adding rt to target_link_libraries fix the problem, thx
